export const tags: string[] = [
    'Environment',
    'Health and Wellness',
    'Youth Programs',
    'Arts and Culture',
    'Crisis',
    'Emergency Response',
    'Elder Care',
    'International',
    'Technology',
    'Recreation',
    'Culture',
    'Food Security',
    'Mental Health',
    'Disability Services',
    'Research',
    'Advocacy',
    'Clean-Up',
    'Humanity',
    'Tutoring',
    'Mentoring',
    'Academics',
    'Animal Shelters',
    'Shelters',
    'Animal',
    'Fundraising',
    'Crisis Hotline',
    'Gardening',
    'Youth',
    'Sports',
    'Coaching',
    'Disaster Relief',
    'Seniors',
    'Food Banks',
    'Nutrition',
    'Education',
    'Music',
    'Science',
    'Job Skills',
    'Online'
];
