services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"

    helper-hive-server:
        image: helper-hive-server
        environment:
            - NODE_ENV=production
            - MONGO_DB_URI=mongodb://mongo:27017/HelperHive
            - ACCESS_CODE_SECRET=${ACCESS_CODE_SECRET:?error}
            - REFRESH_CODE_SECRET=${REFRESH_CODE_SECRET:?error}
            - ACCOUNT_CONFIRMATION_SECRET=${ACCOUNT_CONFIRMATION_SECRET:?error}
            - CLIENT_URL=${CLIENT_URL:?error}
            - DOMAIN=${DOMAIN:?error}
            - AWS_REGION=${AWS_REGION:?error}
            - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:?error}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?error}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?error}
            - SMTP_HOST=${SMTP_HOST:?error}
            - SMTP_USER=${SMTP_USER:?error}
            - SMTP_PASS=${SMTP_PASS:?error}
        ports:
            - "4000:4000"
        depends_on:
            - mongo
